#!/usr/bin/env python3
"""Lay out the programme and write _data/schedule.yml.

Each full day runs to the same shape:

    09:30  keynote (45) + 2 talks
    11:15  coffee (15)
    11:30  2 talks
    12:30  lunch
    14:00  keynote (45) + 2 talks
    15:45  coffee (30)
    16:15  3 talks
    17:45  close

Invited talks are 20 minutes plus 10 for questions. The morning coffee is 15
minutes rather than 30: with a 09:30 start and lunch at 12:30 that is the only
way five morning items fit. A 09:15 start would allow the full 30.

Talks alternate theory and experiment, using the sheet's column, so consecutive
speakers rarely come from the same side. Within each strand the spreadsheet's
order is kept — nothing here knows which talks belong together, so treat this as
a first pass. Once you edit _data/schedule.yml by hand, stop running this.

    python3 scripts/make_schedule.py
"""

import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
KEYNOTE, TALK = 45, 30


def people(data):
    text = (ROOT / "_data" / f"{data}.yml").read_text(encoding="utf-8")
    out = []
    for block in text.split("- name: ")[1:]:
        name = block.split('"')[1]
        field = re.search(r'field: "([^"]*)"', block)
        out.append((name, (field.group(1) if field else "").lower()))
    return out


def interleave(speakers):
    """Alternate theory and experiment, starting with whichever is scarcer."""
    theory = [s for s in speakers if s[1].startswith("theory")]
    experiment = [s for s in speakers if s[1].startswith("experiment")]
    other = [s for s in speakers if s not in theory and s not in experiment]
    short, long_ = sorted((theory, experiment), key=len)
    mixed, i, j = [], 0, 0
    while i < len(short) or j < len(long_):
        if i < len(short):
            mixed.append(short[i]); i += 1
        if j < len(long_):
            mixed.append(long_[j]); j += 1
        # the longer strand gets a second turn when it is more than twice as long
        if j < len(long_) and len(long_) - j > 2 * (len(short) - i):
            mixed.append(long_[j]); j += 1
    return mixed + other


def hhmm(m):
    return f"{m // 60:02d}:{m % 60:02d}"


def main():
    keynotes = [n for n, _ in people("keynotes")]
    talks = interleave(people("speakers"))
    k, t = iter(keynotes), iter(talks)

    def next_keynote():
        return next(k, "Keynote — to be confirmed")

    def next_talk():
        item = next(t, None)
        return item[0] if item else "Open slot"

    lines = [
        "# Generated by scripts/make_schedule.py — a first pass, not a considered",
        "# programme. Rearrange freely; once you edit this by hand, do not re-run it.",
        "",
    ]

    def day(title, rows):
        lines.append(f"- day: {title}")
        lines.append("  slots:")
        for time, kind, what in rows:
            lines.append(f'    - time: "{time}"')
            lines.append(f"      kind: {kind}")
            lines.append(f'      what: "{what}"')

    day("Wednesday 31 March", [
        ("16:30 – 17:00", "break", "Registration and coffee"),
        ("17:00 – 17:45", "keynote", next_keynote()),
        ("17:45", "break", "Drinks reception"),
    ])

    for title in ("Thursday 1 April", "Friday 2 April"):
        rows, clock = [], 9 * 60 + 30

        def slot(length, kind, what):
            nonlocal clock
            rows.append((f"{hhmm(clock)} – {hhmm(clock + length)}", kind, what))
            clock += length

        slot(KEYNOTE, "keynote", next_keynote())
        slot(TALK, "talk", next_talk())
        slot(TALK, "talk", next_talk())
        slot(15, "break", "Coffee")
        slot(TALK, "talk", next_talk())
        slot(TALK, "talk", next_talk())
        rows.append(("12:30 – 14:00", "lunch", "Lunch"))
        clock = 14 * 60
        slot(KEYNOTE, "keynote", next_keynote())
        slot(TALK, "talk", next_talk())
        slot(TALK, "talk", next_talk())
        slot(30, "break", "Coffee")
        slot(TALK, "talk", next_talk())
        slot(TALK, "talk", next_talk())
        slot(TALK, "talk", next_talk())
        rows.append((hhmm(clock), "break", "Close"))
        day(title, rows)

    (ROOT / "_data" / "schedule.yml").write_text("\n".join(lines) + "\n", encoding="utf-8")
    spare = sum(1 for _ in t)
    print(f"{len(keynotes)} keynotes and {len(talks)} talks placed"
          f"{f'; {spare} left over' if spare else ''}")


if __name__ == "__main__":
    main()
