#!/usr/bin/env python3
"""Build the site's people lists from the planning spreadsheet.

The sheet is an invite tracker, not a guest list: it holds wishlist names,
internal notes and people who have not answered. Only rows whose "Confirmed
invite" column starts with "yes" are published — everything else is ignored,
so nobody appears on the site before they have agreed to come.

Writes _data/organizers.yml and _data/speakers.yml (keynotes first, flagged).

    python3 scripts/people_from_sheet.py [--all] [--check]

--all also lists the unconfirmed people, to stdout only, so you can see who is
still outstanding. It never writes them to the site.
"""

import argparse
import csv
import io
import pathlib
import sys
import urllib.request

SHEET_ID = "19YvGkIn0d0KJGLLghzwOQu4ABo0oUkxRCKrMiiHnXs4"
GID = 0
CSV_URL = f"https://docs.google.com/spreadsheets/d/{SHEET_ID}/export?format=csv&gid={GID}"

ROOT = pathlib.Path(__file__).resolve().parent.parent
SECTIONS = {
    "organizers": "organizers",
    "keynote speakers": "keynote",
    "invited speakers": "invited",
    "attendees": "attendees",
}
NAME, SURNAME, INSTITUTION, CONFIRMED = 0, 1, 6, 12

# Photographs, keyed by the name as it appears in the sheet. Each was taken from
# the person's own institutional page after checking the page is really them —
# searching by surname alone lands on the wrong scientist surprisingly often.
# Files live in assets/img/. Anyone not listed here shows their initials instead.
IMAGES = {
    "Andrew Leifer": "andrew-leifer.jpg",              # leiferlab.princeton.edu
    "Agostina Palmigiano": "agostina-palmigiano.jpg",  # palmigianolab.com
    "Arseny Finkelstein": "arseny-finkelstein.jpg",    # english.tau.ac.il
    "Tatiana Engel": "tatiana-engel.jpg",              # simonsfoundation.org
    "Vivek Jayaraman": "vivek-jayaraman.jpg",          # janelia.org
}


def fetch(source=None):
    if source:
        return pathlib.Path(source).read_text(encoding="utf-8")
    with urllib.request.urlopen(CSV_URL, timeout=60) as response:
        return response.read().decode("utf-8")


def cell(row, index):
    return row[index].strip() if len(row) > index else ""


def parse(text):
    people, section = [], None
    for row in csv.reader(io.StringIO(text)):
        cells = [c.strip() for c in row]
        label = " ".join(c for c in cells if c).lower()
        if label in SECTIONS:
            section = SECTIONS[label]
            continue
        name = f"{cell(row, NAME)} {cell(row, SURNAME)}".strip()
        if not name or cell(row, NAME).lower() in ("first name", "name") or section is None:
            continue
        people.append({
            "name": " ".join(name.split()),          # the sheet has stray double spaces
            "institution": cell(row, INSTITUTION),
            "confirmed": cell(row, CONFIRMED).lower().startswith("yes"),
            "section": section,
        })
    return people


def yaml_quote(value):
    return '"' + str(value).replace("\\", "\\\\").replace('"', '\\"') + '"'


def render(people, note):
    lines = [
        "# Generated by scripts/people_from_sheet.py from the planning spreadsheet.",
        "# Only people whose 'Confirmed invite' column says yes appear here.",
        f"# {note}",
        "",
    ]
    for person in people:
        lines.append(f"- name: {yaml_quote(person['name'])}")
        lines.append(f"  affiliation: {yaml_quote(person['institution'])}")
        if person["name"] in IMAGES:
            lines.append(f"  image: {IMAGES[person['name']]}")
        if person.get("keynote"):
            lines.append("  keynote: true")
        lines.append('  # bio: add a sentence or two here, and the card becomes clickable')
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--all", action="store_true", help="also print who has not confirmed")
    parser.add_argument("--from-csv", help="read a local CSV instead of fetching")
    args = parser.parse_args()

    people = parse(fetch(args.from_csv))
    confirmed = [p for p in people if p["confirmed"]]

    organizers = [p for p in confirmed if p["section"] == "organizers"]
    keynotes = [p for p in confirmed if p["section"] == "keynote"]
    invited = [p for p in confirmed if p["section"] == "invited"]
    (ROOT / "_data" / "organizers.yml").write_text(
        render(organizers, "Organisers."), encoding="utf-8")
    (ROOT / "_data" / "keynotes.yml").write_text(
        render(keynotes, "Keynote speakers."), encoding="utf-8")
    (ROOT / "_data" / "speakers.yml").write_text(
        render(invited, "Invited speakers."), encoding="utf-8")

    print(f"published {len(organizers)} organisers, {len(keynotes)} keynotes, "
          f"{len(invited)} invited speakers")

    outstanding = [p for p in people if not p["confirmed"] and p["section"] != "attendees"]
    print(f"held back (not confirmed): {len(outstanding)}")
    if args.all:
        for person in outstanding:
            print(f"   {person['section']:<10} {person['name']:<26} {person['institution']}")


if __name__ == "__main__":
    main()
