#!/usr/bin/env python3
"""Build the site's people lists from the planning spreadsheet.

The sheet is an invite tracker, not a guest list: it holds wishlist names,
internal notes and people who have not answered. Only rows whose "Confirmed attendance"
column starts with "yes" are published — everything else is ignored,
so nobody appears on the site before they have agreed to come.

Writes _data/organizers.yml and _data/speakers.yml (keynotes first, flagged).

    python3 scripts/people_from_sheet.py [--all] [--check]

--all also lists the unconfirmed people, to stdout only, so you can see who is
still outstanding. It never writes them to the site.
"""

import argparse
import csv
import unicodedata
import io
import pathlib
import re
import sys
import urllib.request

SHEET_ID = "19YvGkIn0d0KJGLLghzwOQu4ABo0oUkxRCKrMiiHnXs4"
GID = 0
CSV_URL = f"https://docs.google.com/spreadsheets/d/{SHEET_ID}/export?format=csv&gid={GID}"

ROOT = pathlib.Path(__file__).resolve().parent.parent
SECTIONS = {
    "organizers": "organizers",
    "keynote speakers": "keynote",
    "invited speakers": "invited",
    # A reserve list further down the sheet. Nobody here is published, even when
    # their invite says yes — they are not part of the twenty invited speakers.
    "invited speakers (second tier)": "second tier",
    "attendees": "attendees",
}
# Columns are found by their header, not by position: the sheet gained an
# "Attending" column in September which shifted everything right and silently
# emptied the gate. Publishing is decided by "Confirmed attendance" — somebody
# who accepted the invitation but has not confirmed they are coming does not
# appear on the site.
HEADERS = {
    "first name": "name",
    "last name": "surname",
    "institution": "institution",
    "theory / experiment": "field",
    "confirmed attendance": "attendance",
    "confirmed invite": "invite",
}


def find_columns(rows):
    for row in rows:
        found = {}
        for index, value in enumerate(row):
            key = HEADERS.get(value.strip().lower())
            if key and key not in found:
                found[key] = index
        if "name" in found and "attendance" in found:
            return found
    raise SystemExit("Could not find the header row — has the sheet been restructured?")

AS_KEYNOTE = set()

# Photographs live in assets/img/ as firstname_lastname.jpg. They are matched to
# people by comparing name words rather than by an exact string, because the
# planning sheet's spellings change (Ulises/Ulysses, Edvard/Edward) and one name
# was entered surname-first. A file is used only when it is the single candidate
# sharing a word with that person, so a wrong match cannot slip through quietly.
IMAGE_DIR = ROOT / "assets" / "img"
NOT_A_PERSON = {"hero"}


def name_words(text):
    text = unicodedata.normalize("NFKD", text)
    text = "".join(c for c in text if not unicodedata.combining(c))
    return {w for w in re.split(r"[^A-Za-z]+", text.lower()) if len(w) > 2}


def photo_index():
    index = {}
    for path in sorted(IMAGE_DIR.glob("*.jpg")):
        if path.stem in NOT_A_PERSON:
            continue
        index[path.name] = name_words(path.stem)
    return index


def photo_for(person, index):
    hits = [f for f, words in index.items() if words & name_words(person)]
    return hits[0] if len(hits) == 1 else None



def fetch(source=None):
    if source:
        return pathlib.Path(source).read_text(encoding="utf-8")
    with urllib.request.urlopen(CSV_URL, timeout=60) as response:
        return response.read().decode("utf-8")


def cell(row, index):
    return row[index].strip() if len(row) > index else ""


def parse(text):
    rows = list(csv.reader(io.StringIO(text)))
    columns = find_columns(rows)

    def get(row, key):
        index = columns.get(key)
        return cell(row, index) if index is not None else ""

    people, section = [], None
    for row in rows:
        cells = [c.strip() for c in row]
        label = " ".join(c for c in cells if c).lower()
        if label in SECTIONS:
            section = SECTIONS[label]
            continue
        name = f"{get(row, 'name')} {get(row, 'surname')}".strip()
        if name.lower().startswith("total"):
            continue
        if not name or get(row, "name").lower() in ("first name", "name") or section is None:
            continue
        people.append({
            "name": " ".join(name.split()),          # the sheet has stray double spaces
            "institution": get(row, "institution"),
            "field": get(row, "field"),
            "confirmed": get(row, "attendance").lower().startswith("yes"),
            "section": section,
        })
    return people


def yaml_quote(value):
    return '"' + str(value).replace("\\", "\\\\").replace('"', '\\"') + '"'


def render(people, note):
    render.index = render.index or photo_index()
    lines = [
        "# Generated by scripts/people_from_sheet.py from the planning spreadsheet.",
        "# Only people whose 'Confirmed invite' column says yes appear here.",
        f"# {note}",
        "",
    ]
    for person in people:
        lines.append(f"- name: {yaml_quote(person['name'])}")
        lines.append(f"  affiliation: {yaml_quote(person['institution'])}")
        if person.get("field"):
            lines.append(f"  field: {yaml_quote(person['field'])}")
        photo = photo_for(person["name"], render.index)
        if photo:
            lines.append(f"  image: {photo}")
        if person.get("keynote"):
            lines.append("  keynote: true")
        lines.append('  # bio: add a sentence or two here, and the card becomes clickable')
    return "\n".join(lines) + "\n"


render.index = None


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--all", action="store_true", help="also print who has not confirmed")
    parser.add_argument("--allow-stale", action="store_true",
                        help="keep the committed lists if the sheet cannot be read")
    parser.add_argument("--from-csv", help="read a local CSV instead of fetching")
    args = parser.parse_args()

    try:
        people = parse(fetch(args.from_csv))
    except Exception as error:
        if args.allow_stale and (ROOT / "_data" / "speakers.yml").exists():
            print(f"warning: could not read the sheet ({error}); keeping the lists on disk")
            return
        raise

    # A sheet that parses but yields nobody is far more likely to be a changed
    # layout than a real emptying, so refuse rather than publish a blank page.
    if args.allow_stale and not [p for p in people if p["confirmed"]]:
        print("warning: the sheet produced no confirmed people; keeping the lists on disk")
        return
    confirmed = [p for p in people if p["confirmed"]]

    organizers = [p for p in confirmed if p["section"] == "organizers"]
    # Everyone is gated the same way, keynotes included: the page lists people
    # who have confirmed they are coming, not people who have been invited.
    keynotes = [p for p in confirmed if p["section"] == "keynote"]
    invited = [p for p in confirmed if p["section"] == "invited"]
    (ROOT / "_data" / "organizers.yml").write_text(
        render(organizers, "Organisers."), encoding="utf-8")
    (ROOT / "_data" / "keynotes.yml").write_text(
        render(keynotes, "Keynote speakers."), encoding="utf-8")
    (ROOT / "_data" / "speakers.yml").write_text(
        render(invited, "Invited speakers."), encoding="utf-8")

    print(f"published {len(organizers)} organisers, {len(keynotes)} keynotes, "
          f"{len(invited)} invited speakers")

    outstanding = [p for p in people
                   if not p["confirmed"] and p["section"] not in ("attendees", "keynote")]
    print(f"held back (not confirmed): {len(outstanding)}")
    if args.all:
        for person in outstanding:
            print(f"   {person['section']:<10} {person['name']:<26} {person['institution']}")


if __name__ == "__main__":
    main()
